### ISSUE TITLE
liquidsoap crash after couple of hours when out of memory

### ISSUE THREAD

**Issue by lonerunner** [fyroc/RTMP-Playlist#4]
Hi i follow your guide to stream to nginx with liquidsoap and after a while, liquidsoap crashes and shutdown the stream because the server get out of memory.

The server have 16GB ram and i was checking with "top" command, while streaming liquidsoap slowly over time fill up the ram and after reaching over 30gb in size it crashes, so basically when filling up all ram and swap.

Looking at the log file i don't see anything written into log files about the crash, only usual stuff what video is playing from playlist.

Could you by any chance know the reason or any way how to clean buffer or ram usage so it won't crash constantly.

**Comment by coryfail** [comment]
This is a known issue with Liquidsoap. Try their git page. https://github.com/savonet/liquidsoap/pull/1272
